apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter-deployment
  labels:
    app: node-exporter
spec:
  #replicas: 1
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      hostNetwork: true      
      hostPID: true
      containers:
      - name: node-exporter
        image: quay.io/prometheus/node-exporter:latest 
        ports:
        - containerPort: 9100
        args:
          - "--path.rootfs=/host"
        volumeMounts:
          - name: root
            mountPath: /host:ro,rslave
      volumes:
        - name: root
          hostPath:
            path: /
---
apiVersion: v1
kind: Service
metadata:
  name: node-exporter-service
spec:
  type: NodePort
  selector:
    app: node-exporter
  ports:
    - port: 9100
      targetPort: 9100
      nodePort: 30011
